### ISSUE TITLE
Footer layout mobile

### ISSUE THREAD

**Issue by TimKam** [signavio/tech-blog#30]
On my mobile, the footer looks like this:

![footer_mobile](https://cloud.githubusercontent.com/assets/5434565/23457656/23ca5ec6-fe79-11e6-9511-a65246d11aab.png)

I suggest arranging the items vertically on small-width screens.

**Comment by skalka7** [comment]
Yes, I had this in mind. Didn't have time to change it. If someone wants to take over it's fine, otherwise I will try to fix it as soon as possible.

**Comment by TimKam** [comment]
@skalka7 Ok. We'll see who is faster and should re-assign the issue if somebody else starts working on it.
