### ISSUE TITLE
Track blog impressions

### ISSUE THREAD

**Issue by nfaupel** [signavio/tech-blog#54]
Add tracking params to "jobs" link.

**Comment by hilton** [comment]
What would the tracking data be useful for? I’m not sure if this is worthwhile, if it’s only to satisfy our curiosity.

**Comment by nfaupel** [comment]
If we get more impressions of the Jobs site comming from the blog that from click through our website, we could put more time into the blog promotion.
Can someone estimate the time cost to set this up? I cannot, but with tools like google analytics it should not take too long.

**Comment by hilton** [comment]
> If we get more impressions of the Jobs site comming from the blog that from click through our website, we could put more time into the blog promotion.

Now you're talking about analytics on the jobs site, not on the blog.

**Comment by TimKam** [comment]
Yes. And adding tracking parameters to the "jobs" link on our blog improves analytics for the jobs site. Let's do this. Tracking links for each blog post are too much work imho.

**Comment by sebastian-friedrich** [comment]
Have a talk with Michael Siebert from marketing. He is our full time SEO expert. I think it is better to ask him than fiddeling around if we aim for a professional and reasonable result :-)
