### ISSUE TITLE
Post gallery layout broken on page load

### ISSUE THREAD

**Issue by hilton** [signavio/tech-blog#58]
On my system (Safari 10.1 on macOS 10.12.4), the https://tech.signavio.com layout is broken on page load: some of the post summaries overlap.

![broken layout](https://cloud.githubusercontent.com/assets/232614/24751296/4a6c3132-1ac9-11e7-91a6-e9e06966cdf2.png)

The JavaScript console doesn't show any errors when this happens.

Reloading the page once or twice fixes it. I don't see the same problem on Chrome.

**Comment by skalka7** [comment]
I will look into it, but I don't have so much time this week, so if anyone wants to take over is welcome.

**Comment by skalka7** [comment]
I will try to fix this today, I think it has to do with Google fonts loading.
